### ISSUE TITLE
Table2text support for facebook/opt models

### ISSUE THREAD

**Issue by zredlined** [lxuechen/private-transformers#38]
I am trying to run the examples/table2text using facebook's OPT models but am receiving an error. 

Here is my run script:
```
CUDA_VISIBLE_DEVICES=0 USE_DISTRIBUTED=0 python -m table2text.run_language_modeling \
--num_train_epochs 1 \
--learning_rate 2e-3 \
--per_device_train_batch_size 16 \
--target_delta 8e-6 \
--target_epsilon 8.0 \
--max_seq_len 100 \
--output_dir output_e2e \
--max_train_examples 1e4 \
--max_valid_examples 1e3 \
--max_eval_examples 1e3 \
--overwrite_output_dir \
--task_mode e2e \
--local_rank -1 \
--model_name_or_path "facebook/opt-125m" \
--tokenizer_name "facebook/opt-125m" \
--do_train \
--do_eval \
--line_by_line \
--save_steps 100 \
--save_total_limit 1 \
--save_at_last yes \
--logging_dir output_e2e \
--logging_steps -1 \
--seed 0 \
--eval_steps 100 \
--eval_epochs 2 \
--max_eval_batches 100 \
--evaluation_strategy epoch \
--evaluate_before_training no \
--evaluate_during_training yes \
--per_device_eval_batch_size 10 \
--max_generations 1e5 \
--max_generations_train 1e5 \
--max_generations_valid 1e5 \
--data_folder table2text/prefix-tuning/data/e2e_data \
--format_mode cat \
--per_example_max_grad_norm 0.1 \
--lr_decay no \
--gradient_accumulation_steps 64 \
--non_private no \
--clipping_mode ghost \
--cache_dir cache_dir \
--disable_tqdm no
```

The example above runs fine on my system when using any of the gpt models (e.g. distilgpt2, gpt2), but fails when using the OPT model with the error below:

```
(pt) redlined@aw-fl:~/private-transformers/examples$ sh run_table_to_text.sh 
[2023-06-26 16:32:13,009] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
WARNING:root:Overriding dataset paths using those given in `data_folder`
WARNING:__main__:Process rank: 0, device: cuda:0, n_gpu: 1, distributed training: True, 16-bits training: False
base opt model: facebook/opt-125m
OPTForCausalLM(
  (model): OPTModel(
    (decoder): OPTDecoder(
      (embed_tokens): Embedding(50272, 768, padding_idx=1)
      (embed_positions): OPTLearnedPositionalEmbedding(2050, 768)
      (final_layer_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (layers): ModuleList(
        (0-11): 12 x OPTDecoderLayer(
          (self_attn): OPTAttention(
            (k_proj): Linear(in_features=768, out_features=768, bias=True)
            (v_proj): Linear(in_features=768, out_features=768, bias=True)
            (q_proj): Linear(in_features=768, out_features=768, bias=True)
            (out_proj): Linear(in_features=768, out_features=768, bias=True)
          )
          (activation_fn): ReLU()
          (self_attn_layer_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
          (fc1): Linear(in_features=768, out_features=3072, bias=True)
          (fc2): Linear(in_features=3072, out_features=768, bias=True)
          (final_layer_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        )
      )
    )
  )
  (lm_head): Linear(in_features=768, out_features=50272, bias=False)
)
Cloning initial embedding into lm_head, checking norms... 
        lm_head: 377.95306396484375, embedding: 377.95306396484375
/home/redlined/private-transformers/examples/table2text/run_language_modeling.py:125: FutureWarning: `torch.testing.assert_allclose()` is deprecated since 1.12 and will be removed in a future release. Please use `torch.testing.assert_close()` instead. You can find detailed upgrade instructions in https://github.com/pytorch/pytorch/issues/61844.
  torch.testing.assert_allclose(lm_head.weight, embedding.weight)
adapt tokenizer to include [PAD]
before len(tokenizer) = 50265
after len(tokenizer) = 50266
tokenizer.eos_token: </s> 2
tokenizer.bos_token: </s> 2
adapt the size of lm_head and input_embeddings to include [PAD]
use avg-based initialization
before lm_head.weight.size() = torch.Size([50272, 768]), input_embeddings_before.size() = torch.Size([50272, 768])
after lm_head.weight.size() = torch.Size([50266, 768]), after input_embeddings_after.size() = torch.Size([50266, 768])
/home/redlined/private-transformers/examples/table2text/run_language_modeling.py:158: FutureWarning: `torch.testing.assert_allclose()` is deprecated since 1.12 and will be removed in a future release. Please use `torch.testing.assert_close()` instead. You can find detailed upgrade instructions in https://github.com/pytorch/pytorch/issues/61844.
  torch.testing.assert_allclose(lm_head_before, lm_head_after[:-1])
Traceback (most recent call last):
  File "/opt/conda/envs/pt/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/pt/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/redlined/private-transformers/examples/table2text/run_language_modeling.py", line 313, in <module>
    main()
  File "/home/redlined/private-transformers/examples/table2text/run_language_modeling.py", line 158, in main
    torch.testing.assert_allclose(lm_head_before, lm_head_after[:-1])
  File "/opt/conda/envs/pt/lib/python3.10/site-packages/torch/testing/_comparison.py", line 1553, in assert_allclose
    torch.testing.assert_close(
  File "/opt/conda/envs/pt/lib/python3.10/site-packages/torch/testing/_comparison.py", line 1511, in assert_close
    raise error_metas[0].to_error(msg)
AssertionError: The values for attribute 'shape' do not match: torch.Size([50272, 768]) != torch.Size([50265, 768]).
```

I suspect the problem is around resizing the token embeddings for the OPT model here: https://github.com/zredlined/private-transformers/blob/662cd5c916a5a28f2c99d18c0ad6f1c1c91b2184/examples/table2text/run_language_modeling.py#L146, but I'm not sure why the values would not match.

You can see the changes to support the OPT models in the example table2text script here: https://github.com/zredlined/private-transformers/compare/main...zredlined:private-transformers:aw/table2text-opt?expand=1

Any suggestions would be appreciated. Happy to integrate the code into the existing example script and submit a PR if you'd like. Cheers

**Comment by lxuechen** [comment]
This issue is unrelated to private learning, but I'll comment a little before closing.

OPT model's embedding and tokenizer have different sizes when loaded upfront. For efficiency reasons, HF pads the model's embedding to a multiple of 8, thus size of embedding (50272) > size of tokenizer (50265). This is different from GPT2 where embeddings aren't padded. 

What happens here is that after resizing, the embedding shrank in size. The math goes like 50272 (original size) -> 50265 (shrink to original tokenizer size) -> 50265 + 1 = 50266 (new tokenizer size due to addition of pad token). 

Note the assertion check is to ensure that the old embedding values didn't change after resizing. Given the different padding situations, you should modify this assertion check for OPT.
